## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [7]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Port Hedland,AU,80.60,overcast clouds,-20.3167,118.5667,The Esplanade Hotel
1,6,Rikitea,PF,78.75,clear sky,-23.1203,-134.9692,Pension Maro'i
2,13,Avarua,CK,77.00,scattered clouds,-21.2078,-159.7750,Paradise Inn
3,16,Muzaffargarh,PK,80.60,haze,30.0754,71.1921,Aghosh Hotel
4,20,Cabo San Lucas,MX,77.00,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
...,...,...,...,...,...,...,...,...
207,668,Miramar,US,84.00,broken clouds,25.9873,-80.2323,Miramar
208,671,Gandu,BR,76.75,light rain,-13.7439,-39.4867,Pousada Duarte
209,677,Nouakchott,MR,80.60,overcast clouds,18.0858,-15.9785,HOTEL IMAN فندق إيمان
210,678,Marsh Harbour,BS,76.24,clear sky,26.5412,-77.0636,Abaco Beach Resort
211,679,Badvel,IN,78.04,clear sky,14.7500,79.0500,Venkatalakshuma five star tiffin centre

In [5]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Country Code</dt><dd>{Country}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# 4a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(30,31),zoom_level=1.5)
heat_layer=gmaps.heatmap_layer(locations)
marker_layer=gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
vacation_mx=vacation_df.loc[vacation_df['Country']=="MX"]
vacation_mx

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,20,Cabo San Lucas,MX,77.0,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
31,127,Ixtapa,MX,80.6,clear sky,20.7000,-105.2000,Hotel Plaza Providencia
95,331,Topolobampo,MX,75.2,scattered clouds,25.6000,-109.0500,Hotel Marina Topolobampo
96,332,Ojinaga,MX,77.0,clear sky,29.5667,-104.4167,Suites Las Palmas
133,427,Coahuayana,MX,84.2,clear sky,18.7333,-103.6833,El rranchito michuacan de ocampos

In [11]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Cabo San Lucas')&(vacation_df['Country']=="MX")]
vacation_end = vacation_df.loc[(vacation_df['City']=='Cabo San Lucas')&(vacation_df['Country']=="MX")]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Ixtapa')&(vacation_df['Country']=="MX")]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Topolobampo')&(vacation_df['Country']=="MX")] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Ojinaga')&(vacation_df['Country']=="MX")] 

vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,20,Cabo San Lucas,MX,77.0,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos

In [18]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start["Lat"].to_numpy()[0],vacation_start["Lng"].to_numpy()[0])
end = (vacation_end["Lat"].to_numpy()[0],vacation_end["Lng"].to_numpy()[0])
stop1 = (vacation_stop1["Lat"].to_numpy()[0],vacation_stop1["Lng"].to_numpy()[0])
stop2 = (vacation_stop2["Lat"].to_numpy()[0],vacation_stop2["Lng"].to_numpy()[0])
stop3 = (vacation_stop3["Lat"].to_numpy()[0],vacation_stop3["Lng"].to_numpy()[0])

In [20]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig=gmaps.figure()
city_it=gmaps.directions_layer(
        start, end, waypoints=[stop1,stop2,stop3],
        travel_mode='DRIVING')
fig.add_layer(city_it)
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,20,Cabo San Lucas,MX,77.0,scattered clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
1,127,Ixtapa,MX,80.6,clear sky,20.7000,-105.2000,Hotel Plaza Providencia
2,331,Topolobampo,MX,75.2,scattered clouds,25.6000,-109.0500,Hotel Marina Topolobampo
3,332,Ojinaga,MX,77.0,clear sky,29.5667,-104.4167,Suites Las Palmas

In [24]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Country Code</dt><dd>{Country}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [25]:
# 11a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(30,31),zoom_level=1.5)
heat_layer=gmaps.heatmap_layer(locations)
marker_layer=gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))